version: "3.3"
services:
  db:
    container_name: db_mssql
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    volumes:
      - ./db-data:/var/opt/mssql
    environment:
      SA_PASSWORD: "LAccount@@"
      ACCEPT_EULA: "Y"